services:
  content-oracle:
    container_name: content-oracle
    build:
      context: .
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: https://content-oracle.${ROOT_DOMAIN}
    expose:
      - 80
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.content-oracle.rule=Host(`content-oracle.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.content-oracle.entrypoints=https"
      - "traefik.http.routers.content-oracle.tls.certresolver=le"

networks:
  proxy:
    external: true